server:
  port: 9995

spring:
  application:
    name: spring-boot-admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5