spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: api-gateway

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    max-total-connections: 2000
    max-per-route-connections: 2000
  prefix: /api
  routes:
    auth-service:
      path: /uaa/**
      serviceId: AUTH-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 2000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true


logging:
  file: target/api-gateway.log

#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: web
#      clientSecret: secret
#      accessTokenUri: http://localhost:9991/oauth/tokens
#      userAuthorizationUri: http://localhost:9991/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:9991/resource/user
#      preferTokenInfo: false
#  enable-csrf: false
#  sessions: stateless