server:
  port: 9998

spring:
  application:
    name: user-service-produce

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5